name: Build

on:
  push:
    branches:
      - master

jobs:
  pipeline:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v2
      - uses: aws-actions/setup-sam@v2
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Update local toolchain
        run: |
          rustup update
          rustup component add clippy
          rustup install nightly
          rustup target add x86_64-unknown-linux-musl
          sudo apt-get install -y musl-tools

      - name: Toolchain info
        run: |
          cargo --version --verbose
          rustc --version
          cargo clippy --version
          aws --version
          sam --version

      - name: Lint
        run: |
          cargo fmt -- --check
          cargo clippy -- -D warnings          

      - name: Test
        run: |
          cargo check
          cargo test --all

      - name: Build
        run: |
          sam build
      - name: deploy stack
        run: |
          sam deploy
